version: '3.8'
services:
  weather-api:
    build: .
    container_name: weather-api
    image: weather-image
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - weather-network
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    container_name: weather-postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/DDL.sql:/docker-entrypoint-initdb.d/DDL.sql
    networks:
      - weather-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  weather-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
