-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."LLMArticle"
(
    id integer NOT NULL DEFAULT nextval('"LLMArticle_id_seq"'::regclass),
    location_key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    title character varying(256) COLLATE pg_catalog."default",
    perex character varying(256) COLLATE pg_catalog."default",
    description character varying(2560) COLLATE pg_catalog."default",
    modified_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "LLMArticle_pkey" PRIMARY KEY (id),
    CONSTRAINT "LLMArticle_location_key_key" UNIQUE (location_key)
);

CREATE TABLE IF NOT EXISTS public."LLMArticleAudit"
(
    rev_id integer NOT NULL DEFAULT nextval('"LLMArticlesAudit_rev_id_seq"'::regclass),
    article_id integer NOT NULL,
    location_key character varying(255) COLLATE pg_catalog."default",
    title character varying(256) COLLATE pg_catalog."default",
    perex character varying(512) COLLATE pg_catalog."default",
    description character varying(2560) COLLATE pg_catalog."default",
    modified_at timestamp with time zone,
    created_at timestamp with time zone,
    rev_type "RevType" NOT NULL,
    audit_timestamp timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "LLMArticlesAudit_pkey" PRIMARY KEY (rev_id)
);
END;

-- And this script part is NOT generated by the ERD tool

-- Insert trigger for audit
CREATE OR REPLACE FUNCTION "Trigger_LLMArticle_Insert"()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO "LLMArticleAudit" (
        article_id,
        location_key,
        title,
        perex,
        description,
        modified_at,
        created_at,
        rev_type
    )
    VALUES (
        NEW.id,
        NEW.location_key,
        NEW.title,
        NEW.perex,
        NEW.description,
        NEW.modified_at,
        NEW.created_at,
        'insert'
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;




-- Drop trigger if exists before creating
DROP TRIGGER IF EXISTS "After_LLMArticle_Insert" ON "LLMArticle";
CREATE TRIGGER "After_LLMArticle_Insert"
    AFTER INSERT ON "LLMArticle"
    FOR EACH ROW EXECUTE FUNCTION "Trigger_LLMArticle_Insert"();

-- Update trigger for audit
CREATE OR REPLACE FUNCTION "Trigger_LLMArticle_Update"()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO "LLMArticleAudit" (
        article_id,
        location_key,
        title,
        perex,
        description,
        modified_at,
        created_at,
        rev_type
    )
    VALUES (
        NEW.id,
        NEW.location_key,
        NEW.title,
        NEW.perex,
        NEW.description,
        NEW.modified_at,
        NEW.created_at,
        'update'
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop trigger if exists before creating
DROP TRIGGER IF EXISTS "After_LLMArticle_Update" ON "LLMArticle";
CREATE TRIGGER "After_LLMArticle_Update"
    AFTER UPDATE ON "LLMArticle"
    FOR EACH ROW EXECUTE FUNCTION "Trigger_LLMArticle_Update"();